// Code generated by internal/clonegen; DO NOT EDIT.

package qs

func cloneableStatement(s Statement) bool {
	switch b := s.(type) {
	case *CreateTableAsBuilder:
		return b != nil
	case *DeclareCursorBuilder:
		return b != nil
	case *DeleteBuilder:
		return b != nil
	case *ExecuteBuilder:
		return b != nil
	case *ExplainBuilder:
		return b != nil
	case *InsertAssignments:
		return b != nil
	case *InsertDefaults:
		return b != nil
	case *InsertRows:
		return b != nil
	case *InsertSelect:
		return b != nil
	case *MaterializedViewBuilder:
		return b != nil
	case *MergeBuilder:
		return b != nil
	case *SQLStatement:
		return b != nil
	case *SelectBuilder:
		return b != nil
	case *SelectIntoBuilder:
		return b != nil
	case *SetBuilder:
		return b != nil
	case *TableBuilder:
		return b != nil
	case *TruncateBuilder:
		return b != nil
	case *UpdateBuilder:
		return b != nil
	case *ValuesBuilder:
		return b != nil
	default:
		return false
	}
}

func (c *cloneContext) statement(s Statement) Statement {
	if !cloneableStatement(s) {
		return s
	}
	if v, ok := c.seen[s]; ok {
		return v
	}
	switch v := s.(type) {
	case *CreateTableAsBuilder:
		return c.cloneCreateTableAsBuilder(v)
	case *DeclareCursorBuilder:
		return c.cloneDeclareCursorBuilder(v)
	case *DeleteBuilder:
		return c.cloneDeleteBuilder(v)
	case *ExecuteBuilder:
		return c.cloneExecuteBuilder(v)
	case *ExplainBuilder:
		return c.cloneExplainBuilder(v)
	case *InsertAssignments:
		return c.cloneInsertAssignments(v)
	case *InsertDefaults:
		return c.cloneInsertDefaults(v)
	case *InsertRows:
		return c.cloneInsertRows(v)
	case *InsertSelect:
		return c.cloneInsertSelect(v)
	case *MaterializedViewBuilder:
		return c.cloneMaterializedViewBuilder(v)
	case *MergeBuilder:
		return c.cloneMergeBuilder(v)
	case *SQLStatement:
		return c.cloneSQLStatement(v)
	case *SelectBuilder:
		return c.cloneSelectBuilder(v)
	case *SelectIntoBuilder:
		return c.cloneSelectIntoBuilder(v)
	case *SetBuilder:
		return c.cloneSetBuilder(v)
	case *TableBuilder:
		return c.cloneTableBuilder(v)
	case *TruncateBuilder:
		return c.cloneTruncateBuilder(v)
	case *UpdateBuilder:
		return c.cloneUpdateBuilder(v)
	case *ValuesBuilder:
		return c.cloneValuesBuilder(v)
	default:
		return s
	}
}

func (c *cloneContext) cloneCreateTableAsBuilder(b *CreateTableAsBuilder) *CreateTableAsBuilder {
	n := *b
	c.seen[b] = &n
	n.source = c.utilitySource(b.source)
	n.destination = c.cloneValuecreateTableAsDestination(b.destination)
	return &n
}

func (c *cloneContext) cloneDeclareCursorBuilder(b *DeclareCursorBuilder) *DeclareCursorBuilder {
	n := *b
	c.seen[b] = &n
	n.query = c.rowset(b.query)
	return &n
}

func (c *cloneContext) cloneDeleteBuilder(b *DeleteBuilder) *DeleteBuilder {
	n := *b
	c.seen[b] = &n
	n.aliases = c.cloneValueReturningAliases(b.aliases)
	n.using = cloneSlice(b.using)
	for i1 := range n.using {
		n.using[i1] = c.relation(b.using[i1])
	}
	n.where = cloneSlice(b.where)
	for i1 := range n.where {
		n.where[i1] = c.cloneValueCondition(b.where[i1])
	}
	n.returning = cloneSlice(b.returning)
	for i1 := range n.returning {
		n.returning[i1] = c.expr(b.returning[i1])
	}
	n.table = c.relation(b.table)
	n.base = c.cloneValuestatementBase(b.base)
	return &n
}

func (c *cloneContext) cloneExecuteBuilder(b *ExecuteBuilder) *ExecuteBuilder {
	n := *b
	c.seen[b] = &n
	n.args = cloneSlice(b.args)
	for i1 := range n.args {
		n.args[i1] = c.expr(b.args[i1])
	}
	return &n
}

func (c *cloneContext) cloneExplainBuilder(b *ExplainBuilder) *ExplainBuilder {
	n := *b
	c.seen[b] = &n
	n.query = c.statement(b.query)
	n.options = cloneSlice(b.options)
	return &n
}

func (c *cloneContext) cloneInsertAssignments(b *InsertAssignments) *InsertAssignments {
	n := *b
	c.seen[b] = &n
	n.assignments = cloneSlice(b.assignments)
	for i1 := range n.assignments {
		n.assignments[i1] = c.cloneValueAssignment(b.assignments[i1])
	}
	n.base = c.cloneValueinsertBase(b.base)
	return &n
}

func (c *cloneContext) cloneInsertDefaults(b *InsertDefaults) *InsertDefaults {
	n := *b
	c.seen[b] = &n
	n.base = c.cloneValueinsertBase(b.base)
	return &n
}

func (c *cloneContext) cloneInsertRows(b *InsertRows) *InsertRows {
	n := *b
	c.seen[b] = &n
	n.rows = cloneSlice(b.rows)
	for i1 := range n.rows {
		n.rows[i1] = cloneSlice(b.rows[i1])
		for i2 := range n.rows[i1] {
			n.rows[i1][i2] = c.cloneValueWriteValue(b.rows[i1][i2])
		}
	}
	n.base = c.cloneValueinsertBase(b.base)
	return &n
}

func (c *cloneContext) cloneInsertSelect(b *InsertSelect) *InsertSelect {
	n := *b
	c.seen[b] = &n
	n.source = c.rowset(b.source)
	n.base = c.cloneValueinsertBase(b.base)
	return &n
}

func (c *cloneContext) cloneMaterializedViewBuilder(b *MaterializedViewBuilder) *MaterializedViewBuilder {
	n := *b
	c.seen[b] = &n
	n.query = c.rowset(b.query)
	n.destination = c.cloneValuematerializedViewDestination(b.destination)
	return &n
}

func (c *cloneContext) cloneMergeBuilder(b *MergeBuilder) *MergeBuilder {
	n := *b
	c.seen[b] = &n
	n.aliases = c.cloneValueReturningAliases(b.aliases)
	n.on = cloneSlice(b.on)
	for i1 := range n.on {
		n.on[i1] = c.cloneValueCondition(b.on[i1])
	}
	n.branches = cloneSlice(b.branches)
	for i1 := range n.branches {
		n.branches[i1] = c.cloneValueMergeWhen(b.branches[i1])
	}
	n.returning = cloneSlice(b.returning)
	for i1 := range n.returning {
		n.returning[i1] = c.expr(b.returning[i1])
	}
	n.target = c.relation(b.target)
	n.source = c.relation(b.source)
	n.base = c.cloneValuestatementBase(b.base)
	return &n
}

func (c *cloneContext) cloneSQLStatement(b *SQLStatement) *SQLStatement {
	n := *b
	c.seen[b] = &n
	n.expr = c.expr(b.expr)
	return &n
}

func (c *cloneContext) cloneSelectBuilder(b *SelectBuilder) *SelectBuilder {
	n := *b
	c.seen[b] = &n
	n.columns = cloneSlice(b.columns)
	for i1 := range n.columns {
		n.columns[i1] = c.expr(b.columns[i1])
	}
	n.from = cloneSlice(b.from)
	for i1 := range n.from {
		n.from[i1] = c.relation(b.from[i1])
	}
	n.where = cloneSlice(b.where)
	for i1 := range n.where {
		n.where[i1] = c.cloneValueCondition(b.where[i1])
	}
	n.group = cloneSlice(b.group)
	for i1 := range n.group {
		n.group[i1] = c.expr(b.group[i1])
	}
	n.having = cloneSlice(b.having)
	for i1 := range n.having {
		n.having[i1] = c.cloneValueCondition(b.having[i1])
	}
	n.windows = cloneSlice(b.windows)
	for i1 := range n.windows {
		n.windows[i1] = c.cloneValuenamedWindow(b.windows[i1])
	}
	n.distinctOn = cloneSlice(b.distinctOn)
	for i1 := range n.distinctOn {
		n.distinctOn[i1] = c.expr(b.distinctOn[i1])
	}
	n.tail = c.cloneValuequeryTail(b.tail)
	n.base = c.cloneValuestatementBase(b.base)
	return &n
}

func (c *cloneContext) cloneSelectIntoBuilder(b *SelectIntoBuilder) *SelectIntoBuilder {
	n := *b
	c.seen[b] = &n
	n.source = ownedPayload[*SelectBuilder](c.statement(b.source))
	n.destination = c.cloneValueselectIntoTarget(b.destination)
	return &n
}

func (c *cloneContext) cloneSetBuilder(b *SetBuilder) *SetBuilder {
	n := *b
	c.seen[b] = &n
	n.left = c.rowset(b.left)
	n.right = c.rowset(b.right)
	n.tail = c.cloneValuequeryTail(b.tail)
	n.base = c.cloneValuestatementBase(b.base)
	return &n
}

func (c *cloneContext) cloneTableBuilder(b *TableBuilder) *TableBuilder {
	n := *b
	c.seen[b] = &n
	n.base = c.cloneValuestatementBase(b.base)
	n.table = c.relation(b.table)
	n.tail = c.cloneValuequeryTail(b.tail)
	return &n
}

func (c *cloneContext) cloneTruncateBuilder(b *TruncateBuilder) *TruncateBuilder {
	n := *b
	c.seen[b] = &n
	n.tables = cloneSlice(b.tables)
	for i1 := range n.tables {
		n.tables[i1] = c.relation(b.tables[i1])
	}
	return &n
}

func (c *cloneContext) cloneUpdateBuilder(b *UpdateBuilder) *UpdateBuilder {
	n := *b
	c.seen[b] = &n
	n.aliases = c.cloneValueReturningAliases(b.aliases)
	n.set = cloneSlice(b.set)
	for i1 := range n.set {
		n.set[i1] = c.cloneValueAssignment(b.set[i1])
	}
	n.from = cloneSlice(b.from)
	for i1 := range n.from {
		n.from[i1] = c.relation(b.from[i1])
	}
	n.where = cloneSlice(b.where)
	for i1 := range n.where {
		n.where[i1] = c.cloneValueCondition(b.where[i1])
	}
	n.returning = cloneSlice(b.returning)
	for i1 := range n.returning {
		n.returning[i1] = c.expr(b.returning[i1])
	}
	n.table = c.relation(b.table)
	n.base = c.cloneValuestatementBase(b.base)
	return &n
}

func (c *cloneContext) cloneValuesBuilder(b *ValuesBuilder) *ValuesBuilder {
	n := *b
	c.seen[b] = &n
	n.base = c.cloneValuestatementBase(b.base)
	n.rows = cloneSlice(b.rows)
	for i1 := range n.rows {
		n.rows[i1] = cloneSlice(b.rows[i1])
		for i2 := range n.rows[i1] {
			n.rows[i1][i2] = c.expr(b.rows[i1][i2])
		}
	}
	n.tail = c.cloneValuequeryTail(b.tail)
	return &n
}

func (c *cloneContext) cloneValueAssignment(v Assignment) Assignment {
	n := v
	n.target = c.expr(v.target)
	n.value = c.expr(v.value)
	n.query = c.rowset(v.query)
	n.columns = cloneSlice(v.columns)
	for i1 := range n.columns {
		n.columns[i1] = c.expr(v.columns[i1])
	}
	return n
}

func (c *cloneContext) clonePtrAssignment(v *Assignment) *Assignment {
	if v == nil {
		return nil
	}
	n := c.cloneValueAssignment(*v)
	return &n
}

func (c *cloneContext) cloneValueBound(v Bound) Bound {
	n := v
	n.offset = c.expr(v.offset)
	return n
}

func (c *cloneContext) clonePtrBound(v *Bound) *Bound {
	if v == nil {
		return nil
	}
	n := c.cloneValueBound(*v)
	return &n
}

func (c *cloneContext) cloneValueCondition(v Condition) Condition {
	n := v
	n.expr = c.expr(v.expr)
	return n
}

func (c *cloneContext) clonePtrCondition(v *Condition) *Condition {
	if v == nil {
		return nil
	}
	n := c.cloneValueCondition(*v)
	return &n
}

func (c *cloneContext) cloneValueCycleSpec(v CycleSpec) CycleSpec {
	n := v
	n.to = c.expr(v.to)
	n.otherwise = c.expr(v.otherwise)
	n.columns = cloneSlice(v.columns)
	return n
}

func (c *cloneContext) clonePtrCycleSpec(v *CycleSpec) *CycleSpec {
	if v == nil {
		return nil
	}
	n := c.cloneValueCycleSpec(*v)
	return &n
}

func (c *cloneContext) cloneValueIndexElement(v IndexElement) IndexElement {
	n := v
	n.expr = c.expr(v.expr)
	return n
}

func (c *cloneContext) clonePtrIndexElement(v *IndexElement) *IndexElement {
	if v == nil {
		return nil
	}
	n := c.cloneValueIndexElement(*v)
	return &n
}

func (c *cloneContext) cloneValueJSONBehavior(v JSONBehavior) JSONBehavior {
	n := v
	n.value = c.expr(v.value)
	return n
}

func (c *cloneContext) clonePtrJSONBehavior(v *JSONBehavior) *JSONBehavior {
	if v == nil {
		return nil
	}
	n := c.cloneValueJSONBehavior(*v)
	return &n
}

func (c *cloneContext) cloneValueJSONMember(v JSONMember) JSONMember {
	n := v
	n.key = c.expr(v.key)
	n.value = c.cloneValuejsonConstructorValue(v.value)
	return n
}

func (c *cloneContext) clonePtrJSONMember(v *JSONMember) *JSONMember {
	if v == nil {
		return nil
	}
	n := c.cloneValueJSONMember(*v)
	return &n
}

func (c *cloneContext) cloneValueJSONQueryBuilder(v JSONQueryBuilder) JSONQueryBuilder {
	n := v
	n.document = c.expr(v.document)
	n.path = c.expr(v.path)
	n.passing = cloneSlice(v.passing)
	for i1 := range n.passing {
		n.passing[i1] = c.cloneValuejsonPassing(v.passing[i1])
	}
	n.options = c.cloneValuejsonOptions(v.options)
	return n
}

func (c *cloneContext) clonePtrJSONQueryBuilder(v *JSONQueryBuilder) *JSONQueryBuilder {
	if v == nil {
		return nil
	}
	n := c.cloneValueJSONQueryBuilder(*v)
	return &n
}

func (c *cloneContext) cloneValueJSONTableBuilder(v JSONTableBuilder) JSONTableBuilder {
	n := v
	n.document = c.expr(v.document)
	n.passing = cloneSlice(v.passing)
	for i1 := range n.passing {
		n.passing[i1] = c.cloneValuejsonPassing(v.passing[i1])
	}
	n.columns = cloneSlice(v.columns)
	for i1 := range n.columns {
		n.columns[i1] = c.cloneValueJSONTableColumn(v.columns[i1])
	}
	n.onError = c.cloneValueJSONBehavior(v.onError)
	return n
}

func (c *cloneContext) clonePtrJSONTableBuilder(v *JSONTableBuilder) *JSONTableBuilder {
	if v == nil {
		return nil
	}
	n := c.cloneValueJSONTableBuilder(*v)
	return &n
}

func (c *cloneContext) cloneValueJSONTableColumn(v JSONTableColumn) JSONTableColumn {
	n := v
	n.columns = cloneSlice(v.columns)
	for i1 := range n.columns {
		n.columns[i1] = c.cloneValueJSONTableColumn(v.columns[i1])
	}
	n.options = c.cloneValuejsonOptions(v.options)
	return n
}

func (c *cloneContext) clonePtrJSONTableColumn(v *JSONTableColumn) *JSONTableColumn {
	if v == nil {
		return nil
	}
	n := c.cloneValueJSONTableColumn(*v)
	return &n
}

func (c *cloneContext) cloneValueLockClause(v LockClause) LockClause {
	n := v
	n.of = cloneSlice(v.of)
	return n
}

func (c *cloneContext) clonePtrLockClause(v *LockClause) *LockClause {
	if v == nil {
		return nil
	}
	n := c.cloneValueLockClause(*v)
	return &n
}

func (c *cloneContext) cloneValueMergeWhen(v MergeWhen) MergeWhen {
	n := v
	n.conditions = cloneSlice(v.conditions)
	for i1 := range n.conditions {
		n.conditions[i1] = c.cloneValueCondition(v.conditions[i1])
	}
	n.set = cloneSlice(v.set)
	for i1 := range n.set {
		n.set[i1] = c.cloneValueAssignment(v.set[i1])
	}
	n.columns = cloneSlice(v.columns)
	n.values = cloneSlice(v.values)
	for i1 := range n.values {
		n.values[i1] = c.cloneValueWriteValue(v.values[i1])
	}
	return n
}

func (c *cloneContext) clonePtrMergeWhen(v *MergeWhen) *MergeWhen {
	if v == nil {
		return nil
	}
	n := c.cloneValueMergeWhen(*v)
	return &n
}

func (c *cloneContext) cloneValueOrder(v Order) Order {
	n := v
	n.expr = c.expr(v.expr)
	return n
}

func (c *cloneContext) clonePtrOrder(v *Order) *Order {
	if v == nil {
		return nil
	}
	n := c.cloneValueOrder(*v)
	return &n
}

func (c *cloneContext) cloneValueRecordColumn(v RecordColumn) RecordColumn {
	n := v
	return n
}

func (c *cloneContext) clonePtrRecordColumn(v *RecordColumn) *RecordColumn {
	if v == nil {
		return nil
	}
	n := c.cloneValueRecordColumn(*v)
	return &n
}

func (c *cloneContext) cloneValueRecordFunction(v RecordFunction) RecordFunction {
	n := v
	n.expr = c.expr(v.expr)
	n.columns = cloneSlice(v.columns)
	return n
}

func (c *cloneContext) clonePtrRecordFunction(v *RecordFunction) *RecordFunction {
	if v == nil {
		return nil
	}
	n := c.cloneValueRecordFunction(*v)
	return &n
}

func (c *cloneContext) cloneValueReturningAliases(v ReturningAliases) ReturningAliases {
	n := v
	return n
}

func (c *cloneContext) clonePtrReturningAliases(v *ReturningAliases) *ReturningAliases {
	if v == nil {
		return nil
	}
	n := c.cloneValueReturningAliases(*v)
	return &n
}

func (c *cloneContext) cloneValueSearchSpec(v SearchSpec) SearchSpec {
	n := v
	n.columns = cloneSlice(v.columns)
	return n
}

func (c *cloneContext) clonePtrSearchSpec(v *SearchSpec) *SearchSpec {
	if v == nil {
		return nil
	}
	n := c.cloneValueSearchSpec(*v)
	return &n
}

func (c *cloneContext) cloneValueWindowSpec(v WindowSpec) WindowSpec {
	n := v
	n.partition = cloneSlice(v.partition)
	for i1 := range n.partition {
		n.partition[i1] = c.expr(v.partition[i1])
	}
	n.order = cloneSlice(v.order)
	for i1 := range n.order {
		n.order[i1] = c.cloneValueOrder(v.order[i1])
	}
	n.start = c.cloneValueBound(v.start)
	n.end = c.cloneValueBound(v.end)
	return n
}

func (c *cloneContext) clonePtrWindowSpec(v *WindowSpec) *WindowSpec {
	if v == nil {
		return nil
	}
	n := c.cloneValueWindowSpec(*v)
	return &n
}

func (c *cloneContext) cloneValueWithQuery(v WithQuery) WithQuery {
	n := v
	n.body = c.statement(v.body)
	n.search = c.clonePtrSearchSpec(v.search)
	n.cycle = c.clonePtrCycleSpec(v.cycle)
	n.columns = cloneSlice(v.columns)
	return n
}

func (c *cloneContext) clonePtrWithQuery(v *WithQuery) *WithQuery {
	if v == nil {
		return nil
	}
	n := c.cloneValueWithQuery(*v)
	return &n
}

func (c *cloneContext) cloneValueWriteValue(v WriteValue) WriteValue {
	n := v
	n.write = c.expr(v.write)
	return n
}

func (c *cloneContext) clonePtrWriteValue(v *WriteValue) *WriteValue {
	if v == nil {
		return nil
	}
	n := c.cloneValueWriteValue(*v)
	return &n
}

func (c *cloneContext) cloneValueXMLItem(v XMLItem) XMLItem {
	n := v
	n.value = c.expr(v.value)
	return n
}

func (c *cloneContext) clonePtrXMLItem(v *XMLItem) *XMLItem {
	if v == nil {
		return nil
	}
	n := c.cloneValueXMLItem(*v)
	return &n
}

func (c *cloneContext) cloneValueXMLNamespaceSpec(v XMLNamespaceSpec) XMLNamespaceSpec {
	n := v
	n.uri = c.expr(v.uri)
	return n
}

func (c *cloneContext) clonePtrXMLNamespaceSpec(v *XMLNamespaceSpec) *XMLNamespaceSpec {
	if v == nil {
		return nil
	}
	n := c.cloneValueXMLNamespaceSpec(*v)
	return &n
}

func (c *cloneContext) cloneValueXMLTableBuilder(v XMLTableBuilder) XMLTableBuilder {
	n := v
	n.rowPath = c.expr(v.rowPath)
	n.document = c.expr(v.document)
	n.namespaces = cloneSlice(v.namespaces)
	for i1 := range n.namespaces {
		n.namespaces[i1] = c.cloneValueXMLNamespaceSpec(v.namespaces[i1])
	}
	n.columns = cloneSlice(v.columns)
	for i1 := range n.columns {
		n.columns[i1] = c.cloneValueXMLTableColumn(v.columns[i1])
	}
	return n
}

func (c *cloneContext) clonePtrXMLTableBuilder(v *XMLTableBuilder) *XMLTableBuilder {
	if v == nil {
		return nil
	}
	n := c.cloneValueXMLTableBuilder(*v)
	return &n
}

func (c *cloneContext) cloneValueXMLTableColumn(v XMLTableColumn) XMLTableColumn {
	n := v
	n.path = c.expr(v.path)
	n.defaultExpr = c.expr(v.defaultExpr)
	return n
}

func (c *cloneContext) clonePtrXMLTableColumn(v *XMLTableColumn) *XMLTableColumn {
	if v == nil {
		return nil
	}
	n := c.cloneValueXMLTableColumn(*v)
	return &n
}

func (c *cloneContext) cloneValueaggregateTail(v aggregateTail) aggregateTail {
	n := v
	n.window = c.clonePtrWindowSpec(v.window)
	n.filter = cloneSlice(v.filter)
	for i1 := range n.filter {
		n.filter[i1] = c.cloneValueCondition(v.filter[i1])
	}
	return n
}

func (c *cloneContext) clonePtraggregateTail(v *aggregateTail) *aggregateTail {
	if v == nil {
		return nil
	}
	n := c.cloneValueaggregateTail(*v)
	return &n
}

func (c *cloneContext) cloneValuebetweenExpression(v betweenExpression) betweenExpression {
	n := v
	n.value = c.expr(v.value)
	n.lower = c.expr(v.lower)
	n.upper = c.expr(v.upper)
	return n
}

func (c *cloneContext) clonePtrbetweenExpression(v *betweenExpression) *betweenExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuebetweenExpression(*v)
	return &n
}

func (c *cloneContext) cloneValuecallExpression(v callExpression) callExpression {
	n := v
	n.mods = c.clonePtrcallModifiers(v.mods)
	n.args = cloneSlice(v.args)
	for i1 := range n.args {
		n.args[i1] = c.expr(v.args[i1])
	}
	return n
}

func (c *cloneContext) clonePtrcallExpression(v *callExpression) *callExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuecallExpression(*v)
	return &n
}

func (c *cloneContext) cloneValuecallModifiers(v callModifiers) callModifiers {
	n := v
	n.aggregateTail = c.cloneValueaggregateTail(v.aggregateTail)
	n.order = cloneSlice(v.order)
	for i1 := range n.order {
		n.order[i1] = c.cloneValueOrder(v.order[i1])
	}
	n.within = cloneSlice(v.within)
	for i1 := range n.within {
		n.within[i1] = c.cloneValueOrder(v.within[i1])
	}
	return n
}

func (c *cloneContext) clonePtrcallModifiers(v *callModifiers) *callModifiers {
	if v == nil {
		return nil
	}
	n := c.cloneValuecallModifiers(*v)
	return &n
}

func (c *cloneContext) cloneValuecaseBranch(v caseBranch) caseBranch {
	n := v
	n.when = c.expr(v.when)
	n.then = c.expr(v.then)
	return n
}

func (c *cloneContext) clonePtrcaseBranch(v *caseBranch) *caseBranch {
	if v == nil {
		return nil
	}
	n := c.cloneValuecaseBranch(*v)
	return &n
}

func (c *cloneContext) cloneValuecaseExpression(v caseExpression) caseExpression {
	n := v
	n.operand = c.expr(v.operand)
	n.otherwise = c.expr(v.otherwise)
	n.branches = cloneSlice(v.branches)
	for i1 := range n.branches {
		n.branches[i1] = c.cloneValuecaseBranch(v.branches[i1])
	}
	return n
}

func (c *cloneContext) clonePtrcaseExpression(v *caseExpression) *caseExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuecaseExpression(*v)
	return &n
}

func (c *cloneContext) cloneValuecastExpression(v castExpression) castExpression {
	n := v
	n.expr = c.expr(v.expr)
	return n
}

func (c *cloneContext) clonePtrcastExpression(v *castExpression) *castExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuecastExpression(*v)
	return &n
}

func (c *cloneContext) cloneValueconflictClause(v conflictClause) conflictClause {
	n := v
	n.columns = cloneSlice(v.columns)
	n.index = cloneSlice(v.index)
	for i1 := range n.index {
		n.index[i1] = c.cloneValueIndexElement(v.index[i1])
	}
	n.targetWhere = cloneSlice(v.targetWhere)
	for i1 := range n.targetWhere {
		n.targetWhere[i1] = c.cloneValueCondition(v.targetWhere[i1])
	}
	n.updates = cloneSlice(v.updates)
	for i1 := range n.updates {
		n.updates[i1] = c.cloneValueAssignment(v.updates[i1])
	}
	n.where = cloneSlice(v.where)
	for i1 := range n.where {
		n.where[i1] = c.cloneValueCondition(v.where[i1])
	}
	return n
}

func (c *cloneContext) clonePtrconflictClause(v *conflictClause) *conflictClause {
	if v == nil {
		return nil
	}
	n := c.cloneValueconflictClause(*v)
	return &n
}

func (c *cloneContext) cloneValuecreateTableAsDestination(v createTableAsDestination) createTableAsDestination {
	n := v
	n.columns = cloneSlice(v.columns)
	return n
}

func (c *cloneContext) clonePtrcreateTableAsDestination(v *createTableAsDestination) *createTableAsDestination {
	if v == nil {
		return nil
	}
	n := c.cloneValuecreateTableAsDestination(*v)
	return &n
}

func (c *cloneContext) cloneValueexplainOption(v explainOption) explainOption {
	n := v
	return n
}

func (c *cloneContext) clonePtrexplainOption(v *explainOption) *explainOption {
	if v == nil {
		return nil
	}
	n := c.cloneValueexplainOption(*v)
	return &n
}

func (c *cloneContext) cloneValueexpression(v expression) expression {
	n := v
	n.left = c.expr(v.left)
	n.right = c.expr(v.right)
	return n
}

func (c *cloneContext) clonePtrexpression(v *expression) *expression {
	if v == nil {
		return nil
	}
	n := c.cloneValueexpression(*v)
	return &n
}

func (c *cloneContext) cloneValueinsertBase(v insertBase) insertBase {
	n := v
	n.table = c.relation(v.table)
	n.aliases = c.cloneValueReturningAliases(v.aliases)
	n.conflict = c.clonePtrconflictClause(v.conflict)
	n.returning = cloneSlice(v.returning)
	for i1 := range n.returning {
		n.returning[i1] = c.expr(v.returning[i1])
	}
	n.targets = cloneSlice(v.targets)
	for i1 := range n.targets {
		n.targets[i1] = c.expr(v.targets[i1])
	}
	n.statementBase = c.cloneValuestatementBase(v.statementBase)
	return n
}

func (c *cloneContext) clonePtrinsertBase(v *insertBase) *insertBase {
	if v == nil {
		return nil
	}
	n := c.cloneValueinsertBase(*v)
	return &n
}

func (c *cloneContext) cloneValuejoinExpression(v joinExpression) joinExpression {
	n := v
	n.on = cloneSlice(v.on)
	for i1 := range n.on {
		n.on[i1] = c.cloneValueCondition(v.on[i1])
	}
	n.using = cloneSlice(v.using)
	n.left = c.relation(v.left)
	n.right = c.relation(v.right)
	return n
}

func (c *cloneContext) clonePtrjoinExpression(v *joinExpression) *joinExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuejoinExpression(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonArrayAggregatePayload(v jsonArrayAggregatePayload) jsonArrayAggregatePayload {
	n := v
	n.tail = c.cloneValueaggregateTail(v.tail)
	n.order = cloneSlice(v.order)
	for i1 := range n.order {
		n.order[i1] = c.cloneValueOrder(v.order[i1])
	}
	n.value = c.cloneValuejsonConstructorValue(v.value)
	n.output = c.cloneValuejsonConstructorOutput(v.output)
	return n
}

func (c *cloneContext) clonePtrjsonArrayAggregatePayload(v *jsonArrayAggregatePayload) *jsonArrayAggregatePayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonArrayAggregatePayload(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonArrayConstructorPayload(v jsonArrayConstructorPayload) jsonArrayConstructorPayload {
	n := v
	n.values = cloneSlice(v.values)
	for i1 := range n.values {
		n.values[i1] = c.cloneValuejsonConstructorValue(v.values[i1])
	}
	n.output = c.cloneValuejsonConstructorOutput(v.output)
	return n
}

func (c *cloneContext) clonePtrjsonArrayConstructorPayload(v *jsonArrayConstructorPayload) *jsonArrayConstructorPayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonArrayConstructorPayload(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonArrayQueryPayload(v jsonArrayQueryPayload) jsonArrayQueryPayload {
	n := v
	n.query = c.rowset(v.query)
	n.output = c.cloneValuejsonConstructorOutput(v.output)
	return n
}

func (c *cloneContext) clonePtrjsonArrayQueryPayload(v *jsonArrayQueryPayload) *jsonArrayQueryPayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonArrayQueryPayload(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonConstructorOutput(v jsonConstructorOutput) jsonConstructorOutput {
	n := v
	return n
}

func (c *cloneContext) clonePtrjsonConstructorOutput(v *jsonConstructorOutput) *jsonConstructorOutput {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonConstructorOutput(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonConstructorValue(v jsonConstructorValue) jsonConstructorValue {
	n := v
	n.expr = c.expr(v.expr)
	return n
}

func (c *cloneContext) clonePtrjsonConstructorValue(v *jsonConstructorValue) *jsonConstructorValue {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonConstructorValue(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonIsPredicatePayload(v jsonIsPredicatePayload) jsonIsPredicatePayload {
	n := v
	n.value = c.expr(v.value)
	return n
}

func (c *cloneContext) clonePtrjsonIsPredicatePayload(v *jsonIsPredicatePayload) *jsonIsPredicatePayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonIsPredicatePayload(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonObjectAggregatePayload(v jsonObjectAggregatePayload) jsonObjectAggregatePayload {
	n := v
	n.key = c.cloneValuejsonConstructorValue(v.key)
	n.value = c.cloneValuejsonConstructorValue(v.value)
	n.tail = c.cloneValueaggregateTail(v.tail)
	n.output = c.cloneValuejsonConstructorOutput(v.output)
	return n
}

func (c *cloneContext) clonePtrjsonObjectAggregatePayload(v *jsonObjectAggregatePayload) *jsonObjectAggregatePayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonObjectAggregatePayload(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonObjectConstructorPayload(v jsonObjectConstructorPayload) jsonObjectConstructorPayload {
	n := v
	n.members = cloneSlice(v.members)
	for i1 := range n.members {
		n.members[i1] = c.cloneValueJSONMember(v.members[i1])
	}
	n.output = c.cloneValuejsonConstructorOutput(v.output)
	return n
}

func (c *cloneContext) clonePtrjsonObjectConstructorPayload(v *jsonObjectConstructorPayload) *jsonObjectConstructorPayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonObjectConstructorPayload(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonOptions(v jsonOptions) jsonOptions {
	n := v
	n.empty = c.cloneValueJSONBehavior(v.empty)
	n.onError = c.cloneValueJSONBehavior(v.onError)
	return n
}

func (c *cloneContext) clonePtrjsonOptions(v *jsonOptions) *jsonOptions {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonOptions(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonParsePayload(v jsonParsePayload) jsonParsePayload {
	n := v
	n.value = c.cloneValuejsonConstructorValue(v.value)
	return n
}

func (c *cloneContext) clonePtrjsonParsePayload(v *jsonParsePayload) *jsonParsePayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonParsePayload(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonPassing(v jsonPassing) jsonPassing {
	n := v
	n.value = c.expr(v.value)
	return n
}

func (c *cloneContext) clonePtrjsonPassing(v *jsonPassing) *jsonPassing {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonPassing(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonScalarPayload(v jsonScalarPayload) jsonScalarPayload {
	n := v
	n.value = c.expr(v.value)
	return n
}

func (c *cloneContext) clonePtrjsonScalarPayload(v *jsonScalarPayload) *jsonScalarPayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonScalarPayload(*v)
	return &n
}

func (c *cloneContext) cloneValuejsonSerializePayload(v jsonSerializePayload) jsonSerializePayload {
	n := v
	n.value = c.cloneValuejsonConstructorValue(v.value)
	n.output = c.cloneValuejsonConstructorOutput(v.output)
	return n
}

func (c *cloneContext) clonePtrjsonSerializePayload(v *jsonSerializePayload) *jsonSerializePayload {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonSerializePayload(*v)
	return &n
}

func (c *cloneContext) cloneValuematerializedViewDestination(v materializedViewDestination) materializedViewDestination {
	n := v
	n.columns = cloneSlice(v.columns)
	return n
}

func (c *cloneContext) clonePtrmaterializedViewDestination(v *materializedViewDestination) *materializedViewDestination {
	if v == nil {
		return nil
	}
	n := c.cloneValuematerializedViewDestination(*v)
	return &n
}

func (c *cloneContext) cloneValuemembershipExpression(v membershipExpression) membershipExpression {
	n := v
	n.left = c.expr(v.left)
	n.query = c.rowset(v.query)
	n.values = cloneSlice(v.values)
	for i1 := range n.values {
		n.values[i1] = c.expr(v.values[i1])
	}
	return n
}

func (c *cloneContext) clonePtrmembershipExpression(v *membershipExpression) *membershipExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuemembershipExpression(*v)
	return &n
}

func (c *cloneContext) cloneValuenamedWindow(v namedWindow) namedWindow {
	n := v
	n.spec = c.cloneValueWindowSpec(v.spec)
	return n
}

func (c *cloneContext) clonePtrnamedWindow(v *namedWindow) *namedWindow {
	if v == nil {
		return nil
	}
	n := c.cloneValuenamedWindow(*v)
	return &n
}

func (c *cloneContext) cloneValuequeryTail(v queryTail) queryTail {
	n := v
	n.limit = c.expr(v.limit)
	n.offset = c.expr(v.offset)
	n.fetch = c.expr(v.fetch)
	n.order = cloneSlice(v.order)
	for i1 := range n.order {
		n.order[i1] = c.cloneValueOrder(v.order[i1])
	}
	n.locks = cloneSlice(v.locks)
	for i1 := range n.locks {
		n.locks[i1] = c.cloneValueLockClause(v.locks[i1])
	}
	return n
}

func (c *cloneContext) clonePtrqueryTail(v *queryTail) *queryTail {
	if v == nil {
		return nil
	}
	n := c.cloneValuequeryTail(*v)
	return &n
}

func (c *cloneContext) cloneValuesampleClause(v sampleClause) sampleClause {
	n := v
	n.seed = c.expr(v.seed)
	n.arguments = cloneSlice(v.arguments)
	for i1 := range n.arguments {
		n.arguments[i1] = c.expr(v.arguments[i1])
	}
	return n
}

func (c *cloneContext) clonePtrsampleClause(v *sampleClause) *sampleClause {
	if v == nil {
		return nil
	}
	n := c.cloneValuesampleClause(*v)
	return &n
}

func (c *cloneContext) cloneValueselectIntoTarget(v selectIntoTarget) selectIntoTarget {
	n := v
	return n
}

func (c *cloneContext) clonePtrselectIntoTarget(v *selectIntoTarget) *selectIntoTarget {
	if v == nil {
		return nil
	}
	n := c.cloneValueselectIntoTarget(*v)
	return &n
}

func (c *cloneContext) cloneValuesliceExpression(v sliceExpression) sliceExpression {
	n := v
	n.value = c.expr(v.value)
	n.lower = c.expr(v.lower)
	n.upper = c.expr(v.upper)
	return n
}

func (c *cloneContext) clonePtrsliceExpression(v *sliceExpression) *sliceExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuesliceExpression(*v)
	return &n
}

func (c *cloneContext) cloneValuesqlSyntaxExpression(v sqlSyntaxExpression) sqlSyntaxExpression {
	n := v
	n.args = cloneSlice(v.args)
	for i1 := range n.args {
		n.args[i1] = c.expr(v.args[i1])
	}
	return n
}

func (c *cloneContext) clonePtrsqlSyntaxExpression(v *sqlSyntaxExpression) *sqlSyntaxExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuesqlSyntaxExpression(*v)
	return &n
}

func (c *cloneContext) cloneValuestatementBase(v statementBase) statementBase {
	n := v
	n.with = cloneSlice(v.with)
	for i1 := range n.with {
		n.with[i1] = c.cloneValueWithQuery(v.with[i1])
	}
	n.prefix = cloneSlice(v.prefix)
	for i1 := range n.prefix {
		n.prefix[i1] = c.expr(v.prefix[i1])
	}
	n.suffix = cloneSlice(v.suffix)
	for i1 := range n.suffix {
		n.suffix[i1] = c.expr(v.suffix[i1])
	}
	return n
}

func (c *cloneContext) clonePtrstatementBase(v *statementBase) *statementBase {
	if v == nil {
		return nil
	}
	n := c.cloneValuestatementBase(*v)
	return &n
}

func (c *cloneContext) cloneValuesubqueryExpression(v subqueryExpression) subqueryExpression {
	n := v
	n.query = c.rowset(v.query)
	return n
}

func (c *cloneContext) clonePtrsubqueryExpression(v *subqueryExpression) *subqueryExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuesubqueryExpression(*v)
	return &n
}

func (c *cloneContext) cloneValueversionedExpression(v versionedExpression) versionedExpression {
	n := v
	n.expr = c.expr(v.expr)
	return n
}

func (c *cloneContext) clonePtrversionedExpression(v *versionedExpression) *versionedExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValueversionedExpression(*v)
	return &n
}

func (c *cloneContext) cloneValuexmlExpression(v xmlExpression) xmlExpression {
	n := v
	n.value = c.expr(v.value)
	n.path = c.expr(v.path)
	n.document = c.expr(v.document)
	n.version = c.expr(v.version)
	n.items = cloneSlice(v.items)
	for i1 := range n.items {
		n.items[i1] = c.cloneValueXMLItem(v.items[i1])
	}
	n.values = cloneSlice(v.values)
	for i1 := range n.values {
		n.values[i1] = c.expr(v.values[i1])
	}
	return n
}

func (c *cloneContext) clonePtrxmlExpression(v *xmlExpression) *xmlExpression {
	if v == nil {
		return nil
	}
	n := c.cloneValuexmlExpression(*v)
	return &n
}

func (c *cloneContext) expr(e Expr) Expr {
	n := e
	n.node = c.clonePtrexpression(e.node)
	n.value = c.cloneExprPayload(e.kind, e.value)
	return n
}

func (c *cloneContext) cloneExprPayload(kind exprKind, value any) any {
	switch kind {
	case exprAlias:
		return value
	case exprBetween:
		return c.clonePtrbetweenExpression(ownedPayload[*betweenExpression](value))
	case exprBinary:
		return value
	case exprCall:
		return c.clonePtrcallExpression(ownedPayload[*callExpression](value))
	case exprCase:
		return c.clonePtrcaseExpression(ownedPayload[*caseExpression](value))
	case exprCast:
		return c.clonePtrcastExpression(ownedPayload[*castExpression](value))
	case exprCollate:
		return value
	case exprExists:
		return c.clonePtrsubqueryExpression(ownedPayload[*subqueryExpression](value))
	case exprField:
		return value
	case exprFields:
		return value
	case exprFragment:
		return c.cloneExprs(ownedPayload[[]Expr](value))
	case exprGroup:
		return c.cloneExprs(ownedPayload[[]Expr](value))
	case exprIdentifier:
		return value
	case exprIdentifierParts:
		return identifierParts(cloneSlice(ownedPayload[identifierParts](value)))
	case exprInvalid:
		return value
	case exprJSONConstructor:
		return c.clonePtrjsonConstructor(ownedPayload[*jsonConstructor](value))
	case exprKeyword:
		return value
	case exprList:
		return c.cloneExprs(ownedPayload[[]Expr](value))
	case exprLiteral:
		return value
	case exprMembership:
		return c.clonePtrmembershipExpression(ownedPayload[*membershipExpression](value))
	case exprParameter:
		return value
	case exprPostfix:
		return value
	case exprPrefix:
		return value
	case exprQuantified:
		return value
	case exprRaw:
		return value
	case exprSQLJSON:
		return c.clonePtrJSONQueryBuilder(ownedPayload[*JSONQueryBuilder](value))
	case exprSQLSyntax:
		return c.clonePtrsqlSyntaxExpression(ownedPayload[*sqlSyntaxExpression](value))
	case exprSlice:
		return c.clonePtrsliceExpression(ownedPayload[*sliceExpression](value))
	case exprSpecialCall:
		return value
	case exprStringLiteral:
		return value
	case exprSubquery:
		return c.clonePtrsubqueryExpression(ownedPayload[*subqueryExpression](value))
	case exprSubscript:
		return value
	case exprVersioned:
		return c.clonePtrversionedExpression(ownedPayload[*versionedExpression](value))
	case exprXML:
		return c.clonePtrxmlExpression(ownedPayload[*xmlExpression](value))
	default:
		return value
	}
}

func (c *cloneContext) cloneExprs(v []Expr) []Expr {
	n := cloneSlice(v)
	for i := range n {
		n[i] = c.expr(v[i])
	}
	return n
}

func (c *cloneContext) relation(r Relation) Relation {
	n := r
	n.columns = cloneSlice(r.columns)
	n.sample = c.clonePtrsampleClause(r.sample)
	n.value = c.cloneRelationPayload(r.kind, r.value)
	return n
}

func (c *cloneContext) cloneRelationPayload(kind relationKind, value any) any {
	if value == nil {
		return nil
	}
	switch kind {
	case relationFunction:
		return c.cloneValueRecordFunction(ownedPayload[RecordFunction](value))
	case relationJSONTable:
		return c.clonePtrJSONTableBuilder(ownedPayload[*JSONTableBuilder](value))
	case relationJoin:
		return c.clonePtrjoinExpression(ownedPayload[*joinExpression](value))
	case relationRowsFrom:
		n := cloneSlice(ownedPayload[[]RecordFunction](value))
		for i := range n {
			n[i] = c.cloneValueRecordFunction(n[i])
		}
		return n
	case relationSQL:
		return c.expr(ownedPayload[Expr](value))
	case relationSubquery:
		return ownedPayload[Rowset](c.rowset(ownedPayload[Rowset](value)))
	case relationTable:
		return value
	case relationTableIdent:
		return identifierParts(cloneSlice(ownedPayload[identifierParts](value)))
	case relationXMLTable:
		return c.clonePtrXMLTableBuilder(ownedPayload[*XMLTableBuilder](value))
	default:
		return value
	}
}

func (c *cloneContext) cloneValuejsonConstructor(v jsonConstructor) jsonConstructor {
	n := v
	n.payload = c.cloneJSONPayload(v.kind, v.payload)
	return n
}

func (c *cloneContext) clonePtrjsonConstructor(v *jsonConstructor) *jsonConstructor {
	if v == nil {
		return nil
	}
	n := c.cloneValuejsonConstructor(*v)
	return &n
}

func (c *cloneContext) cloneJSONPayload(kind jsonConstructorKind, value any) any {
	switch kind {
	case jsonArrayAggregate:
		return c.clonePtrjsonArrayAggregatePayload(ownedPayload[*jsonArrayAggregatePayload](value))
	case jsonArrayConstructor:
		return c.clonePtrjsonArrayConstructorPayload(ownedPayload[*jsonArrayConstructorPayload](value))
	case jsonArrayQueryConstructor:
		return c.clonePtrjsonArrayQueryPayload(ownedPayload[*jsonArrayQueryPayload](value))
	case jsonIsPredicate:
		return c.clonePtrjsonIsPredicatePayload(ownedPayload[*jsonIsPredicatePayload](value))
	case jsonObjectAggregate:
		return c.clonePtrjsonObjectAggregatePayload(ownedPayload[*jsonObjectAggregatePayload](value))
	case jsonObjectConstructor:
		return c.clonePtrjsonObjectConstructorPayload(ownedPayload[*jsonObjectConstructorPayload](value))
	case jsonParseConstructor:
		return c.clonePtrjsonParsePayload(ownedPayload[*jsonParsePayload](value))
	case jsonScalarConstructor:
		return c.clonePtrjsonScalarPayload(ownedPayload[*jsonScalarPayload](value))
	case jsonSerializeConstructor:
		return c.clonePtrjsonSerializePayload(ownedPayload[*jsonSerializePayload](value))
	default:
		return value
	}
}

func (c *cloneContext) rows(v [][]Expr) [][]Expr {
	n := cloneSlice(v)
	for i := range n {
		n[i] = c.cloneExprs(v[i])
	}
	return n
}

func (c *cloneContext) exprs(v []Expr) []Expr { return c.cloneExprs(v) }

func (c *cloneContext) rowset(s Rowset) Rowset {
	if s == nil {
		return nil
	}
	return ownedPayload[Rowset](c.statement(s))
}
