// Code generated by scripts/generate.py; DO NOT EDIT.

package qs

// With appends ctes to b in order, mutates b, and returns b. Duplicate CTE names are reported when b is rendered.
func (b *SelectBuilder) With(ctes ...WithQuery) *SelectBuilder {
	b.base.with = append(b.base.with, ctes...)
	return b
}

// WithRecursive marks b as using WITH RECURSIVE, appends ctes in order, mutates b, and returns b.
func (b *SelectBuilder) WithRecursive(ctes ...WithQuery) *SelectBuilder {
	b.base.recursive = true
	b.base.with = append(b.base.with, ctes...)
	return b
}

// Prefix appends parts before b's statement body, mutates b, and returns b.
func (b *SelectBuilder) Prefix(parts ...Expr) *SelectBuilder {
	b.base.prefix = append(b.base.prefix, parts...)
	return b
}

// Suffix appends parts after b's statement body, mutates b, and returns b.
func (b *SelectBuilder) Suffix(parts ...Expr) *SelectBuilder {
	b.base.suffix = append(b.base.suffix, parts...)
	return b
}

// As wraps b as a Relation subquery with alias and optional column aliases. The relation retains b as its source, and the column aliases are copied.
func (b *SelectBuilder) As(alias string, columns ...string) Relation {
	return Subquery(b, alias, columns...)
}

// OrderBy appends terms to b's ORDER BY list, mutates b, and returns b.
func (b *SelectBuilder) OrderBy(terms ...Order) *SelectBuilder {
	b.tail.order = append(b.tail.order, terms...)
	return b
}

// RemoveOrderBy clears b's ORDER BY list, mutates b, and returns b.
func (b *SelectBuilder) RemoveOrderBy() *SelectBuilder {
	clear(b.tail.order)
	b.tail.order = b.tail.order[:0]
	return b
}

// Limit replaces b's LIMIT with a bound integer count, mutates b, and returns b. A negative count causes rendering to fail. LIMIT and FETCH are mutually exclusive.
func (b *SelectBuilder) Limit(count int) *SelectBuilder { return b.LimitExpr(limitValue(count)) }

// LimitExpr replaces b's LIMIT with count, mutates b, and returns b. The expression is validated while rendering.
func (b *SelectBuilder) LimitExpr(count Expr) *SelectBuilder {
	b.tail.limit = count
	b.tail.hasLimit = true
	b.tail.limitAll = false
	return b
}

// RemoveLimit removes b's LIMIT, including LIMIT ALL, mutates b, and returns b.
func (b *SelectBuilder) RemoveLimit() *SelectBuilder {
	b.tail.limit = Expr{}
	b.tail.hasLimit = false
	b.tail.limitAll = false
	return b
}

// Offset replaces b's OFFSET with a bound integer count, mutates b, and returns b. A negative count causes rendering to fail.
func (b *SelectBuilder) Offset(count int) *SelectBuilder { return b.OffsetExpr(limitValue(count)) }

// OffsetExpr replaces b's OFFSET with count, mutates b, and returns b. The expression is validated while rendering.
func (b *SelectBuilder) OffsetExpr(count Expr) *SelectBuilder {
	b.tail.offset = count
	b.tail.hasOffset = true
	return b
}

// RemoveOffset removes b's OFFSET, mutates b, and returns b.
func (b *SelectBuilder) RemoveOffset() *SelectBuilder {
	b.tail.offset = Expr{}
	b.tail.hasOffset = false
	return b
}

// LimitAll replaces b's LIMIT with LIMIT ALL, mutates b, and returns b. LIMIT and FETCH are mutually exclusive.
func (b *SelectBuilder) LimitAll() *SelectBuilder {
	b.tail.limit = Expr{}
	b.tail.hasLimit = true
	b.tail.limitAll = true
	return b
}

// Fetch replaces b's FETCH clause with a bound integer count and mode, mutates b, and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. LIMIT and FETCH are mutually exclusive.
func (b *SelectBuilder) Fetch(count int, mode FetchMode) *SelectBuilder {
	return b.FetchExpr(limitValue(count), mode)
}

// FetchExpr replaces b's FETCH clause with count and mode, mutates b, and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. LIMIT and FETCH are mutually exclusive.
func (b *SelectBuilder) FetchExpr(count Expr, mode FetchMode) *SelectBuilder {
	b.tail.fetch = count
	b.tail.hasFetch = true
	b.tail.fetchMode = mode
	return b
}

// RemoveFetch removes b's FETCH clause, mutates b, and returns b.
func (b *SelectBuilder) RemoveFetch() *SelectBuilder {
	b.tail.fetch = Expr{}
	b.tail.hasFetch = false
	return b
}

// Lock appends row-lock clauses to b, mutates b, and returns b. It is supported by SELECT and TABLE statements; invalid combinations fail when rendered.
func (b *SelectBuilder) Lock(clauses ...LockClause) *SelectBuilder {
	b.tail.locks = append(b.tail.locks, clauses...)
	return b
}

// With appends ctes to b in order, mutates b, and returns b. Duplicate CTE names are reported when b is rendered.
func (b *InsertBuilder) With(ctes ...WithQuery) *InsertBuilder {
	b.base.with = append(b.base.with, ctes...)
	return b
}

// WithRecursive marks b as using WITH RECURSIVE, appends ctes in order, mutates b, and returns b.
func (b *InsertBuilder) WithRecursive(ctes ...WithQuery) *InsertBuilder {
	b.base.recursive = true
	b.base.with = append(b.base.with, ctes...)
	return b
}

// Prefix appends parts before b's statement body, mutates b, and returns b.
func (b *InsertBuilder) Prefix(parts ...Expr) *InsertBuilder {
	b.base.prefix = append(b.base.prefix, parts...)
	return b
}

// Suffix appends parts after b's statement body, mutates b, and returns b.
func (b *InsertBuilder) Suffix(parts ...Expr) *InsertBuilder {
	b.base.suffix = append(b.base.suffix, parts...)
	return b
}

// With appends ctes to b in order, mutates b, and returns b. Duplicate CTE names are reported when b is rendered.
func (b *UpdateBuilder) With(ctes ...WithQuery) *UpdateBuilder {
	b.base.with = append(b.base.with, ctes...)
	return b
}

// WithRecursive marks b as using WITH RECURSIVE, appends ctes in order, mutates b, and returns b.
func (b *UpdateBuilder) WithRecursive(ctes ...WithQuery) *UpdateBuilder {
	b.base.recursive = true
	b.base.with = append(b.base.with, ctes...)
	return b
}

// Prefix appends parts before b's statement body, mutates b, and returns b.
func (b *UpdateBuilder) Prefix(parts ...Expr) *UpdateBuilder {
	b.base.prefix = append(b.base.prefix, parts...)
	return b
}

// Suffix appends parts after b's statement body, mutates b, and returns b.
func (b *UpdateBuilder) Suffix(parts ...Expr) *UpdateBuilder {
	b.base.suffix = append(b.base.suffix, parts...)
	return b
}

// With appends ctes to b in order, mutates b, and returns b. Duplicate CTE names are reported when b is rendered.
func (b *DeleteBuilder) With(ctes ...WithQuery) *DeleteBuilder {
	b.base.with = append(b.base.with, ctes...)
	return b
}

// WithRecursive marks b as using WITH RECURSIVE, appends ctes in order, mutates b, and returns b.
func (b *DeleteBuilder) WithRecursive(ctes ...WithQuery) *DeleteBuilder {
	b.base.recursive = true
	b.base.with = append(b.base.with, ctes...)
	return b
}

// Prefix appends parts before b's statement body, mutates b, and returns b.
func (b *DeleteBuilder) Prefix(parts ...Expr) *DeleteBuilder {
	b.base.prefix = append(b.base.prefix, parts...)
	return b
}

// Suffix appends parts after b's statement body, mutates b, and returns b.
func (b *DeleteBuilder) Suffix(parts ...Expr) *DeleteBuilder {
	b.base.suffix = append(b.base.suffix, parts...)
	return b
}

// With appends ctes to b in order, mutates b, and returns b. Duplicate CTE names are reported when b is rendered.
func (b *MergeBuilder) With(ctes ...WithQuery) *MergeBuilder {
	b.base.with = append(b.base.with, ctes...)
	return b
}

// Prefix appends parts before b's statement body, mutates b, and returns b.
func (b *MergeBuilder) Prefix(parts ...Expr) *MergeBuilder {
	b.base.prefix = append(b.base.prefix, parts...)
	return b
}

// Suffix appends parts after b's statement body, mutates b, and returns b.
func (b *MergeBuilder) Suffix(parts ...Expr) *MergeBuilder {
	b.base.suffix = append(b.base.suffix, parts...)
	return b
}

// With appends ctes to b in order, mutates b, and returns b. Duplicate CTE names are reported when b is rendered.
func (b *SetBuilder) With(ctes ...WithQuery) *SetBuilder {
	b.base.with = append(b.base.with, ctes...)
	return b
}

// WithRecursive marks b as using WITH RECURSIVE, appends ctes in order, mutates b, and returns b.
func (b *SetBuilder) WithRecursive(ctes ...WithQuery) *SetBuilder {
	b.base.recursive = true
	b.base.with = append(b.base.with, ctes...)
	return b
}

// Prefix appends parts before b's statement body, mutates b, and returns b.
func (b *SetBuilder) Prefix(parts ...Expr) *SetBuilder {
	b.base.prefix = append(b.base.prefix, parts...)
	return b
}

// Suffix appends parts after b's statement body, mutates b, and returns b.
func (b *SetBuilder) Suffix(parts ...Expr) *SetBuilder {
	b.base.suffix = append(b.base.suffix, parts...)
	return b
}

// As wraps b as a Relation subquery with alias and optional column aliases. The relation retains b as its source, and the column aliases are copied.
func (b *SetBuilder) As(alias string, columns ...string) Relation {
	return Subquery(b, alias, columns...)
}

// OrderBy appends terms to b's ORDER BY list, mutates b, and returns b.
func (b *SetBuilder) OrderBy(terms ...Order) *SetBuilder {
	b.tail.order = append(b.tail.order, terms...)
	return b
}

// RemoveOrderBy clears b's ORDER BY list, mutates b, and returns b.
func (b *SetBuilder) RemoveOrderBy() *SetBuilder {
	clear(b.tail.order)
	b.tail.order = b.tail.order[:0]
	return b
}

// Limit replaces b's LIMIT with a bound integer count, mutates b, and returns b. A negative count causes rendering to fail. LIMIT and FETCH are mutually exclusive.
func (b *SetBuilder) Limit(count int) *SetBuilder { return b.LimitExpr(limitValue(count)) }

// LimitExpr replaces b's LIMIT with count, mutates b, and returns b. The expression is validated while rendering.
func (b *SetBuilder) LimitExpr(count Expr) *SetBuilder {
	b.tail.limit = count
	b.tail.hasLimit = true
	b.tail.limitAll = false
	return b
}

// RemoveLimit removes b's LIMIT, including LIMIT ALL, mutates b, and returns b.
func (b *SetBuilder) RemoveLimit() *SetBuilder {
	b.tail.limit = Expr{}
	b.tail.hasLimit = false
	b.tail.limitAll = false
	return b
}

// Offset replaces b's OFFSET with a bound integer count, mutates b, and returns b. A negative count causes rendering to fail.
func (b *SetBuilder) Offset(count int) *SetBuilder { return b.OffsetExpr(limitValue(count)) }

// OffsetExpr replaces b's OFFSET with count, mutates b, and returns b. The expression is validated while rendering.
func (b *SetBuilder) OffsetExpr(count Expr) *SetBuilder {
	b.tail.offset = count
	b.tail.hasOffset = true
	return b
}

// RemoveOffset removes b's OFFSET, mutates b, and returns b.
func (b *SetBuilder) RemoveOffset() *SetBuilder {
	b.tail.offset = Expr{}
	b.tail.hasOffset = false
	return b
}

// LimitAll replaces b's LIMIT with LIMIT ALL, mutates b, and returns b. LIMIT and FETCH are mutually exclusive.
func (b *SetBuilder) LimitAll() *SetBuilder {
	b.tail.limit = Expr{}
	b.tail.hasLimit = true
	b.tail.limitAll = true
	return b
}

// Fetch replaces b's FETCH clause with a bound integer count and mode, mutates b, and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. LIMIT and FETCH are mutually exclusive.
func (b *SetBuilder) Fetch(count int, mode FetchMode) *SetBuilder {
	return b.FetchExpr(limitValue(count), mode)
}

// FetchExpr replaces b's FETCH clause with count and mode, mutates b, and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. LIMIT and FETCH are mutually exclusive.
func (b *SetBuilder) FetchExpr(count Expr, mode FetchMode) *SetBuilder {
	b.tail.fetch = count
	b.tail.hasFetch = true
	b.tail.fetchMode = mode
	return b
}

// RemoveFetch removes b's FETCH clause, mutates b, and returns b.
func (b *SetBuilder) RemoveFetch() *SetBuilder {
	b.tail.fetch = Expr{}
	b.tail.hasFetch = false
	return b
}

// With appends ctes to b in order, mutates b, and returns b. Duplicate CTE names are reported when b is rendered.
func (b *ValuesBuilder) With(ctes ...WithQuery) *ValuesBuilder {
	b.base.with = append(b.base.with, ctes...)
	return b
}

// WithRecursive marks b as using WITH RECURSIVE, appends ctes in order, mutates b, and returns b.
func (b *ValuesBuilder) WithRecursive(ctes ...WithQuery) *ValuesBuilder {
	b.base.recursive = true
	b.base.with = append(b.base.with, ctes...)
	return b
}

// Prefix appends parts before b's statement body, mutates b, and returns b.
func (b *ValuesBuilder) Prefix(parts ...Expr) *ValuesBuilder {
	b.base.prefix = append(b.base.prefix, parts...)
	return b
}

// Suffix appends parts after b's statement body, mutates b, and returns b.
func (b *ValuesBuilder) Suffix(parts ...Expr) *ValuesBuilder {
	b.base.suffix = append(b.base.suffix, parts...)
	return b
}

// As wraps b as a Relation subquery with alias and optional column aliases. The relation retains b as its source, and the column aliases are copied.
func (b *ValuesBuilder) As(alias string, columns ...string) Relation {
	return Subquery(b, alias, columns...)
}

// OrderBy appends terms to b's ORDER BY list, mutates b, and returns b.
func (b *ValuesBuilder) OrderBy(terms ...Order) *ValuesBuilder {
	b.tail.order = append(b.tail.order, terms...)
	return b
}

// RemoveOrderBy clears b's ORDER BY list, mutates b, and returns b.
func (b *ValuesBuilder) RemoveOrderBy() *ValuesBuilder {
	clear(b.tail.order)
	b.tail.order = b.tail.order[:0]
	return b
}

// Limit replaces b's LIMIT with a bound integer count, mutates b, and returns b. A negative count causes rendering to fail. LIMIT and FETCH are mutually exclusive.
func (b *ValuesBuilder) Limit(count int) *ValuesBuilder { return b.LimitExpr(limitValue(count)) }

// LimitExpr replaces b's LIMIT with count, mutates b, and returns b. The expression is validated while rendering.
func (b *ValuesBuilder) LimitExpr(count Expr) *ValuesBuilder {
	b.tail.limit = count
	b.tail.hasLimit = true
	b.tail.limitAll = false
	return b
}

// RemoveLimit removes b's LIMIT, including LIMIT ALL, mutates b, and returns b.
func (b *ValuesBuilder) RemoveLimit() *ValuesBuilder {
	b.tail.limit = Expr{}
	b.tail.hasLimit = false
	b.tail.limitAll = false
	return b
}

// Offset replaces b's OFFSET with a bound integer count, mutates b, and returns b. A negative count causes rendering to fail.
func (b *ValuesBuilder) Offset(count int) *ValuesBuilder { return b.OffsetExpr(limitValue(count)) }

// OffsetExpr replaces b's OFFSET with count, mutates b, and returns b. The expression is validated while rendering.
func (b *ValuesBuilder) OffsetExpr(count Expr) *ValuesBuilder {
	b.tail.offset = count
	b.tail.hasOffset = true
	return b
}

// RemoveOffset removes b's OFFSET, mutates b, and returns b.
func (b *ValuesBuilder) RemoveOffset() *ValuesBuilder {
	b.tail.offset = Expr{}
	b.tail.hasOffset = false
	return b
}

// LimitAll replaces b's LIMIT with LIMIT ALL, mutates b, and returns b. LIMIT and FETCH are mutually exclusive.
func (b *ValuesBuilder) LimitAll() *ValuesBuilder {
	b.tail.limit = Expr{}
	b.tail.hasLimit = true
	b.tail.limitAll = true
	return b
}

// Fetch replaces b's FETCH clause with a bound integer count and mode, mutates b, and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. LIMIT and FETCH are mutually exclusive.
func (b *ValuesBuilder) Fetch(count int, mode FetchMode) *ValuesBuilder {
	return b.FetchExpr(limitValue(count), mode)
}

// FetchExpr replaces b's FETCH clause with count and mode, mutates b, and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. LIMIT and FETCH are mutually exclusive.
func (b *ValuesBuilder) FetchExpr(count Expr, mode FetchMode) *ValuesBuilder {
	b.tail.fetch = count
	b.tail.hasFetch = true
	b.tail.fetchMode = mode
	return b
}

// RemoveFetch removes b's FETCH clause, mutates b, and returns b.
func (b *ValuesBuilder) RemoveFetch() *ValuesBuilder {
	b.tail.fetch = Expr{}
	b.tail.hasFetch = false
	return b
}

// With appends ctes to b in order, mutates b, and returns b. Duplicate CTE names are reported when b is rendered.
func (b *TableBuilder) With(ctes ...WithQuery) *TableBuilder {
	b.base.with = append(b.base.with, ctes...)
	return b
}

// WithRecursive marks b as using WITH RECURSIVE, appends ctes in order, mutates b, and returns b.
func (b *TableBuilder) WithRecursive(ctes ...WithQuery) *TableBuilder {
	b.base.recursive = true
	b.base.with = append(b.base.with, ctes...)
	return b
}

// Prefix appends parts before b's statement body, mutates b, and returns b.
func (b *TableBuilder) Prefix(parts ...Expr) *TableBuilder {
	b.base.prefix = append(b.base.prefix, parts...)
	return b
}

// Suffix appends parts after b's statement body, mutates b, and returns b.
func (b *TableBuilder) Suffix(parts ...Expr) *TableBuilder {
	b.base.suffix = append(b.base.suffix, parts...)
	return b
}

// As wraps b as a Relation subquery with alias and optional column aliases. The relation retains b as its source, and the column aliases are copied.
func (b *TableBuilder) As(alias string, columns ...string) Relation {
	return Subquery(b, alias, columns...)
}

// OrderBy appends terms to b's ORDER BY list, mutates b, and returns b.
func (b *TableBuilder) OrderBy(terms ...Order) *TableBuilder {
	b.tail.order = append(b.tail.order, terms...)
	return b
}

// RemoveOrderBy clears b's ORDER BY list, mutates b, and returns b.
func (b *TableBuilder) RemoveOrderBy() *TableBuilder {
	clear(b.tail.order)
	b.tail.order = b.tail.order[:0]
	return b
}

// Limit replaces b's LIMIT with a bound integer count, mutates b, and returns b. A negative count causes rendering to fail. LIMIT and FETCH are mutually exclusive.
func (b *TableBuilder) Limit(count int) *TableBuilder { return b.LimitExpr(limitValue(count)) }

// LimitExpr replaces b's LIMIT with count, mutates b, and returns b. The expression is validated while rendering.
func (b *TableBuilder) LimitExpr(count Expr) *TableBuilder {
	b.tail.limit = count
	b.tail.hasLimit = true
	b.tail.limitAll = false
	return b
}

// RemoveLimit removes b's LIMIT, including LIMIT ALL, mutates b, and returns b.
func (b *TableBuilder) RemoveLimit() *TableBuilder {
	b.tail.limit = Expr{}
	b.tail.hasLimit = false
	b.tail.limitAll = false
	return b
}

// Offset replaces b's OFFSET with a bound integer count, mutates b, and returns b. A negative count causes rendering to fail.
func (b *TableBuilder) Offset(count int) *TableBuilder { return b.OffsetExpr(limitValue(count)) }

// OffsetExpr replaces b's OFFSET with count, mutates b, and returns b. The expression is validated while rendering.
func (b *TableBuilder) OffsetExpr(count Expr) *TableBuilder {
	b.tail.offset = count
	b.tail.hasOffset = true
	return b
}

// RemoveOffset removes b's OFFSET, mutates b, and returns b.
func (b *TableBuilder) RemoveOffset() *TableBuilder {
	b.tail.offset = Expr{}
	b.tail.hasOffset = false
	return b
}

// LimitAll replaces b's LIMIT with LIMIT ALL, mutates b, and returns b. LIMIT and FETCH are mutually exclusive.
func (b *TableBuilder) LimitAll() *TableBuilder {
	b.tail.limit = Expr{}
	b.tail.hasLimit = true
	b.tail.limitAll = true
	return b
}

// Fetch replaces b's FETCH clause with a bound integer count and mode, mutates b, and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. LIMIT and FETCH are mutually exclusive.
func (b *TableBuilder) Fetch(count int, mode FetchMode) *TableBuilder {
	return b.FetchExpr(limitValue(count), mode)
}

// FetchExpr replaces b's FETCH clause with count and mode, mutates b, and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. LIMIT and FETCH are mutually exclusive.
func (b *TableBuilder) FetchExpr(count Expr, mode FetchMode) *TableBuilder {
	b.tail.fetch = count
	b.tail.hasFetch = true
	b.tail.fetchMode = mode
	return b
}

// RemoveFetch removes b's FETCH clause, mutates b, and returns b.
func (b *TableBuilder) RemoveFetch() *TableBuilder {
	b.tail.fetch = Expr{}
	b.tail.hasFetch = false
	return b
}

// Lock appends row-lock clauses to b, mutates b, and returns b. It is supported by SELECT and TABLE statements; invalid combinations fail when rendered.
func (b *TableBuilder) Lock(clauses ...LockClause) *TableBuilder {
	b.tail.locks = append(b.tail.locks, clauses...)
	return b
}
