// Code generated by scripts/generate.py; DO NOT EDIT.

package qs

func (*SelectBuilder) statement()                      {}
func (b *SelectBuilder) Clone() *SelectBuilder         { return Clone(b) }
func (b *SelectBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *SelectBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *SelectBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *SelectBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}
func (*SelectBuilder) rowset() {}

func (*InsertBuilder) statement()                      {}
func (b *InsertBuilder) Clone() *InsertBuilder         { return Clone(b) }
func (b *InsertBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *InsertBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *InsertBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *InsertBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*UpdateBuilder) statement()                      {}
func (b *UpdateBuilder) Clone() *UpdateBuilder         { return Clone(b) }
func (b *UpdateBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *UpdateBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *UpdateBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *UpdateBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*DeleteBuilder) statement()                      {}
func (b *DeleteBuilder) Clone() *DeleteBuilder         { return Clone(b) }
func (b *DeleteBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *DeleteBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *DeleteBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *DeleteBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*MergeBuilder) statement()                      {}
func (b *MergeBuilder) Clone() *MergeBuilder          { return Clone(b) }
func (b *MergeBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *MergeBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *MergeBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *MergeBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*SetBuilder) statement()                                         {}
func (b *SetBuilder) Clone() *SetBuilder                               { return Clone(b) }
func (b *SetBuilder) ToSQL() (string, []any, error)                    { return ToSQL(b) }
func (b *SetBuilder) ToSQLWith(options Options) (string, []any, error) { return ToSQLWith(b, options) }
func (b *SetBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *SetBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}
func (*SetBuilder) rowset() {}

func (*ValuesBuilder) statement()                      {}
func (b *ValuesBuilder) Clone() *ValuesBuilder         { return Clone(b) }
func (b *ValuesBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *ValuesBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *ValuesBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *ValuesBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}
func (*ValuesBuilder) rowset() {}

func (*TableBuilder) statement()                      {}
func (b *TableBuilder) Clone() *TableBuilder          { return Clone(b) }
func (b *TableBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *TableBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *TableBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *TableBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}
func (*TableBuilder) rowset() {}

func (*ExplainBuilder) statement()                      {}
func (b *ExplainBuilder) Clone() *ExplainBuilder        { return Clone(b) }
func (b *ExplainBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *ExplainBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *ExplainBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *ExplainBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*TruncateBuilder) statement()                      {}
func (b *TruncateBuilder) Clone() *TruncateBuilder       { return Clone(b) }
func (b *TruncateBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *TruncateBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *TruncateBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *TruncateBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*ExecuteBuilder) statement()                      {}
func (b *ExecuteBuilder) Clone() *ExecuteBuilder        { return Clone(b) }
func (b *ExecuteBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *ExecuteBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *ExecuteBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *ExecuteBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*CreateTableAsBuilder) statement()                      {}
func (b *CreateTableAsBuilder) Clone() *CreateTableAsBuilder  { return Clone(b) }
func (b *CreateTableAsBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *CreateTableAsBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *CreateTableAsBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *CreateTableAsBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*MaterializedViewBuilder) statement()                        {}
func (b *MaterializedViewBuilder) Clone() *MaterializedViewBuilder { return Clone(b) }
func (b *MaterializedViewBuilder) ToSQL() (string, []any, error)   { return ToSQL(b) }
func (b *MaterializedViewBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *MaterializedViewBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *MaterializedViewBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*DeclareCursorBuilder) statement()                      {}
func (b *DeclareCursorBuilder) Clone() *DeclareCursorBuilder  { return Clone(b) }
func (b *DeclareCursorBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *DeclareCursorBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *DeclareCursorBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *DeclareCursorBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*SelectIntoBuilder) statement()                      {}
func (b *SelectIntoBuilder) Clone() *SelectIntoBuilder     { return Clone(b) }
func (b *SelectIntoBuilder) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *SelectIntoBuilder) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *SelectIntoBuilder) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *SelectIntoBuilder) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}

func (*SQLStatement) statement()                      {}
func (b *SQLStatement) Clone() *SQLStatement          { return Clone(b) }
func (b *SQLStatement) ToSQL() (string, []any, error) { return ToSQL(b) }
func (b *SQLStatement) ToSQLWith(options Options) (string, []any, error) {
	return ToSQLWith(b, options)
}
func (b *SQLStatement) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {
	return AppendSQL(sql, args, b)
}

// AppendWith renders with options into caller-owned SQL and argument storage.
func (b *SQLStatement) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {
	return AppendWith(sql, args, b, options)
}
