// Code generated by scripts/generate.py; DO NOT EDIT.

package qx

// Tuple2Expr is a statically typed SQL row of degree 2.
type Tuple2Expr[A any, B any] struct{ row RowExpr }

func Tuple2[A any, B any](a Field[A], b Field[B]) Tuple2Expr[A, B] {
	return Tuple2Expr[A, B]{row: Row(a.expr, b.expr)}
}
func (r Tuple2Expr[A, B]) Expr() Expr                   { return r.row.Expr() }
func (r Tuple2Expr[A, B]) EqValues(a A, b B) Condition  { return r.row.EqValues(a, b) }
func (r Tuple2Expr[A, B]) NeValues(a A, b B) Condition  { return r.row.NeValues(a, b) }
func (r Tuple2Expr[A, B]) LtValues(a A, b B) Condition  { return r.row.LtValues(a, b) }
func (r Tuple2Expr[A, B]) LteValues(a A, b B) Condition { return r.row.LteValues(a, b) }
func (r Tuple2Expr[A, B]) GtValues(a A, b B) Condition  { return r.row.GtValues(a, b) }
func (r Tuple2Expr[A, B]) GteValues(a A, b B) Condition { return r.row.GteValues(a, b) }

// Tuple3Expr is a statically typed SQL row of degree 3.
type Tuple3Expr[A any, B any, C any] struct{ row RowExpr }

func Tuple3[A any, B any, C any](a Field[A], b Field[B], c Field[C]) Tuple3Expr[A, B, C] {
	return Tuple3Expr[A, B, C]{row: Row(a.expr, b.expr, c.expr)}
}
func (r Tuple3Expr[A, B, C]) Expr() Expr                        { return r.row.Expr() }
func (r Tuple3Expr[A, B, C]) EqValues(a A, b B, c C) Condition  { return r.row.EqValues(a, b, c) }
func (r Tuple3Expr[A, B, C]) NeValues(a A, b B, c C) Condition  { return r.row.NeValues(a, b, c) }
func (r Tuple3Expr[A, B, C]) LtValues(a A, b B, c C) Condition  { return r.row.LtValues(a, b, c) }
func (r Tuple3Expr[A, B, C]) LteValues(a A, b B, c C) Condition { return r.row.LteValues(a, b, c) }
func (r Tuple3Expr[A, B, C]) GtValues(a A, b B, c C) Condition  { return r.row.GtValues(a, b, c) }
func (r Tuple3Expr[A, B, C]) GteValues(a A, b B, c C) Condition { return r.row.GteValues(a, b, c) }

// Tuple4Expr is a statically typed SQL row of degree 4.
type Tuple4Expr[A any, B any, C any, D any] struct{ row RowExpr }

func Tuple4[A any, B any, C any, D any](a Field[A], b Field[B], c Field[C], d Field[D]) Tuple4Expr[A, B, C, D] {
	return Tuple4Expr[A, B, C, D]{row: Row(a.expr, b.expr, c.expr, d.expr)}
}
func (r Tuple4Expr[A, B, C, D]) Expr() Expr { return r.row.Expr() }
func (r Tuple4Expr[A, B, C, D]) EqValues(a A, b B, c C, d D) Condition {
	return r.row.EqValues(a, b, c, d)
}
func (r Tuple4Expr[A, B, C, D]) NeValues(a A, b B, c C, d D) Condition {
	return r.row.NeValues(a, b, c, d)
}
func (r Tuple4Expr[A, B, C, D]) LtValues(a A, b B, c C, d D) Condition {
	return r.row.LtValues(a, b, c, d)
}
func (r Tuple4Expr[A, B, C, D]) LteValues(a A, b B, c C, d D) Condition {
	return r.row.LteValues(a, b, c, d)
}
func (r Tuple4Expr[A, B, C, D]) GtValues(a A, b B, c C, d D) Condition {
	return r.row.GtValues(a, b, c, d)
}
func (r Tuple4Expr[A, B, C, D]) GteValues(a A, b B, c C, d D) Condition {
	return r.row.GteValues(a, b, c, d)
}
