#!/usr/bin/env python3
"""Generate mechanical builder methods; does not inspect application schemas."""
from pathlib import Path
import subprocess
root = Path(__file__).resolve().parent.parent
header = '// Code generated by scripts/generate.py; DO NOT EDIT.\n\npackage qx\n\n'
rowsets = {'SelectBuilder','SetBuilder','ValuesBuilder','TableBuilder'}
builders = ['SelectBuilder','InsertBuilder','UpdateBuilder','DeleteBuilder','MergeBuilder','SetBuilder','ValuesBuilder','TableBuilder']
all_types = builders+[
    'ExplainBuilder',
    'TruncateBuilder',
    'ExecuteBuilder',
    'CreateTableAsBuilder',
    'MaterializedViewBuilder',
    'DeclareCursorBuilder',
    'SelectIntoBuilder',
    'SQLStatement',
]
lines = [header]
for t in all_types:
    lines += [f'func (*{t}) statement() {{}}\n',
              f'func (b *{t}) Clone() *{t} {{ return Clone(b) }}\n',
              f'func (b *{t}) ToSQL() (string, []any, error) {{ return ToSQL(b) }}\n',
              f'func (b *{t}) ToSQLWith(options Options) (string, []any, error) {{ return ToSQLWith(b,options) }}\n',
              f'func (b *{t}) AppendSQL(sql []byte, args []any) ([]byte, []any, error) {{ return AppendSQL(sql,args,b) }}\n',
              '// AppendWith renders with options into caller-owned SQL and argument storage.\n',
              f'func (b *{t}) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error) {{ return AppendWith(sql,args,b,options) }}\n']
    if t in rowsets: lines += [f'func (*{t}) rowset() {{}}\n']
    lines += ['\n']
(root/'statement_methods.go').write_text(''.join(lines))
lines = [header]
for t in builders:
    def method(name, args, body, result=None):
        lines.append(f'func (b *{t}) {name}({args}) {result or "*"+t} {{ {body} }}\n')
    method('With','ctes ...WithQuery','b.base.with=append(b.base.with,ctes...); return b')
    if t != 'MergeBuilder': method('WithRecursive','ctes ...WithQuery','b.base.recursive=true; b.base.with=append(b.base.with,ctes...); return b')
    method('Prefix','parts ...Expr','b.base.prefix=append(b.base.prefix,parts...); return b')
    method('Suffix','parts ...Expr','b.base.suffix=append(b.base.suffix,parts...); return b')
    if t in rowsets:
        method('As','alias string,columns ...string','return Subquery(b,alias,columns...)','Relation')
        method('OrderBy','terms ...Order','b.tail.order=append(b.tail.order,terms...); return b')
        method('RemoveOrderBy','','clear(b.tail.order); b.tail.order=b.tail.order[:0]; return b')
        method('Limit','count int','return b.LimitExpr(limitValue(count))')
        method('LimitExpr','count Expr','b.tail.limit=count; b.tail.hasLimit=true; b.tail.limitAll=false; return b')
        method('RemoveLimit','','b.tail.limit=Expr{}; b.tail.hasLimit=false; b.tail.limitAll=false; return b')
        method('Offset','count int','return b.OffsetExpr(limitValue(count))')
        method('OffsetExpr','count Expr','b.tail.offset=count; b.tail.hasOffset=true; return b')
        method('RemoveOffset','','b.tail.offset=Expr{}; b.tail.hasOffset=false; return b')
        method('LimitAll','','b.tail.limit=Expr{}; b.tail.hasLimit=true; b.tail.limitAll=true; return b')
        method('Fetch','count int,mode FetchMode','return b.FetchExpr(limitValue(count),mode)')
        method('FetchExpr','count Expr,mode FetchMode','b.tail.fetch=count; b.tail.hasFetch=true; b.tail.fetchMode=mode; return b')
        method('RemoveFetch','','b.tail.fetch=Expr{}; b.tail.hasFetch=false; return b')
        if t in {'SelectBuilder','TableBuilder'}: method('Lock','clauses ...LockClause','b.tail.locks=append(b.tail.locks,clauses...); return b')
    lines += ['\n']
(root/'fluent.go').write_text(''.join(lines))
subprocess.run(['gofmt','-w',str(root/'fluent.go'),str(root/'statement_methods.go')],check=True)

# Typed row helpers deliberately stop at arity four; arbitrary-degree Row is
# available without code generation. Values retain their individual Go types.
lines = [header]
for degree in range(2,5):
    letters = [chr(ord('A')+i) for i in range(degree)]
    vars = [x.lower() for x in letters]
    params = ', '.join(x+' any' for x in letters)
    types = ', '.join(letters)
    fields = ', '.join(f'{v} Field[{t}]' for v,t in zip(vars,letters))
    values = ', '.join(f'{v} {t}' for v,t in zip(vars,letters))
    actual = ', '.join(vars)
    exprs = ', '.join(v+'.expr' for v in vars)
    typename = f'Tuple{degree}Expr'
    lines.append(f'// {typename} is a statically typed SQL row of degree {degree}.\n')
    lines.append(f'type {typename}[{params}] struct {{ row RowExpr }}\n')
    lines.append(f'func Tuple{degree}[{params}]({fields}) {typename}[{types}] {{ return {typename}[{types}]{{row:Row({exprs})}} }}\n')
    lines.append(f'func (r {typename}[{types}]) Expr() Expr {{ return r.row.Expr() }}\n')
    for op in ('Eq','Ne','Lt','Lte','Gt','Gte'):
        lines.append(f'func (r {typename}[{types}]) {op}Values({values}) Condition {{ return r.row.{op}Values({actual}) }}\n')
(root/'tuple.go').write_text(''.join(lines))
subprocess.run(['gofmt','-w',str(root/'tuple.go')],check=True)
