#!/usr/bin/env python3
"""Generate mechanical builder methods; does not inspect application schemas."""
from pathlib import Path
import subprocess
import sys
root = Path(__file__).resolve().parent.parent
header = '// Code generated by scripts/generate.py; DO NOT EDIT.\n\npackage qs\n\n'

check = '--check' in sys.argv[1:]


def emit(path, content):
    """Format generated Go and either write it or verify it is current."""
    formatted = subprocess.run(
        ['gofmt'], input=content, text=True, capture_output=True, check=True
    ).stdout
    if check:
        try:
            current = path.read_text()
        except FileNotFoundError:
            current = None
        if current != formatted:
            raise SystemExit(f'{path.relative_to(root)} is stale; run make generate')
        return
    path.write_text(formatted)


rowsets = {'SelectBuilder','SetBuilder','ValuesBuilder','TableBuilder'}
insert_roles = ['InsertRows', 'InsertSelect', 'InsertAssignments', 'InsertDefaults']
insert_override_roles = {'InsertRows', 'InsertSelect', 'InsertAssignments'}
builders = ['SelectBuilder'] + insert_roles + ['UpdateBuilder','DeleteBuilder','MergeBuilder','SetBuilder','ValuesBuilder','TableBuilder']
all_types = builders+[
    'ExplainBuilder',
    'TruncateBuilder',
    'ExecuteBuilder',
    'CreateTableAsBuilder',
    'MaterializedViewBuilder',
    'DeclareCursorBuilder',
    'SelectIntoBuilder',
    'SQLStatement',
]
def doc(lines, name, text):
    """Append a GoDoc comment for an exported declaration."""
    lines.append(f'// {name} {text}\n')


statement_method_docs = {
    'Clone': (
        'returns a copy of b with its builder graph duplicated. Shared subqueries '
        'and cycles remain shared in the copy, while bound application values are '
        'shallow-copied. Do not mutate b concurrently with Clone.'
    ),
    'ToSQL': (
        'renders b with the default Options. It returns no SQL or arguments when '
        'rendering fails.'
    ),
    'ToSQLWith': (
        'renders b with options. It returns no SQL or arguments when rendering '
        'fails.'
    ),
    'AppendSQL': (
        'appends b to caller-owned sql and args with the default Options. Parameter '
        'numbering starts after the existing arguments; an error leaves the input '
        'slices unchanged.'
    ),
    'AppendWith': (
        'appends b to caller-owned sql and args with options. Parameter numbering '
        'starts after the existing arguments; an error leaves the input slices '
        'unchanged.'
    ),
}


fluent_method_docs = {
    'With': (
        'appends ctes to b in order, mutates b, and returns b. Duplicate CTE names '
        'are reported when b is rendered.'
    ),
    'WithRecursive': (
        'marks b as using WITH RECURSIVE, appends ctes in order, mutates b, and '
        'returns b.'
    ),
    'Prefix': (
        "appends parts before b's statement body, mutates b, and returns b."
    ),
    'Suffix': (
        "appends parts after b's statement body, mutates b, and returns b."
    ),
    'As': (
        'wraps b as a Relation subquery with alias and optional column aliases. '
        'The relation retains b as its source, and the column aliases are copied.'
    ),
    'OrderBy': (
        "appends terms to b's ORDER BY list, mutates b, and returns b."
    ),
    'RemoveOrderBy': (
        "clears b's ORDER BY list, mutates b, and returns b."
    ),
    'Limit': (
        "replaces b's LIMIT with a bound integer count, mutates b, and returns b. "
        'A negative count causes rendering to fail. LIMIT and FETCH are mutually '
        'exclusive.'
    ),
    'LimitExpr': (
        "replaces b's LIMIT with count, mutates b, and returns b. The expression "
        'is validated while rendering.'
    ),
    'RemoveLimit': (
        "removes b's LIMIT, including LIMIT ALL, mutates b, and returns b."
    ),
    'Offset': (
        "replaces b's OFFSET with a bound integer count, mutates b, and returns b. "
        'A negative count causes rendering to fail.'
    ),
    'OffsetExpr': (
        "replaces b's OFFSET with count, mutates b, and returns b. The expression "
        'is validated while rendering.'
    ),
    'RemoveOffset': (
        "removes b's OFFSET, mutates b, and returns b."
    ),
    'LimitAll': (
        "replaces b's LIMIT with LIMIT ALL, mutates b, and returns b. LIMIT and "
        'FETCH are mutually exclusive.'
    ),
    'Fetch': (
        "replaces b's FETCH clause with a bound integer count and mode, mutates b, "
        'and returns b. WithTies requires ORDER BY, PostgreSQL 13 or newer, and no '
        'row locks. LIMIT and FETCH are mutually exclusive.'
    ),
    'FetchExpr': (
        "replaces b's FETCH clause with count and mode, mutates b, and returns b. "
        'WithTies requires ORDER BY, PostgreSQL 13 or newer, and no row locks. '
        'LIMIT and FETCH are mutually exclusive.'
    ),
    'RemoveFetch': (
        "removes b's FETCH clause, mutates b, and returns b."
    ),
    'Lock': (
        'appends row-lock clauses to b, mutates b, and returns b. It is supported '
        'by SELECT and TABLE statements; invalid combinations fail when rendered.'
    ),
    'Into': (
        'replaces the INSERT target table, mutates b, and returns b.'
    ),
    'Columns': (
        'selects an immutable ordinary INSERT target-column list before choosing a source.'
    ),
    'Targets': (
        'selects an immutable INSERT target-expression list before choosing a source.'
    ),
    'Values': (
        'selects a direct INSERT value-row source and returns its completed role.'
    ),
    'From': (
        'selects an INSERT rowset source and returns its completed role.'
    ),
    'DefaultValues': (
        "selects the INSERT target table's server-side defaults and returns its completed role."
    ),
    'OverridingSystemValue': (
        'allows explicit values for GENERATED ALWAYS identities, mutates b, and returns b.'
    ),
    'OverridingUserValue': (
        'requests generated identity values in place of supplied values, mutates b, and returns b.'
    ),
    'OnConflict': (
        'sets the completed ON CONFLICT action, mutates b, and returns b.'
    ),
    'Returning': (
        'appends expressions to the RETURNING projection, mutates b, and returns b.'
    ),
    'ReturningCols': (
        'appends named columns to the RETURNING projection, mutates b, and returns b.'
    ),
    'ReturningRows': (
        'replaces the OLD and NEW RETURNING row aliases, mutates b, and returns b.'
    ),
}


lines = [header]
for t in all_types:
    lines.append(f'func (*{t}) statement() {{}}\n')
    for name, signature, body in [
        ('Clone', f'func (b *{t}) Clone() *{t}', 'return Clone(b)'),
        ('ToSQL', f'func (b *{t}) ToSQL() (string, []any, error)', 'return ToSQL(b)'),
        ('ToSQLWith', f'func (b *{t}) ToSQLWith(options Options) (string, []any, error)', 'return ToSQLWith(b,options)'),
        ('AppendSQL', f'func (b *{t}) AppendSQL(sql []byte, args []any) ([]byte, []any, error)', 'return AppendSQL(sql,args,b)'),
        ('AppendWith', f'func (b *{t}) AppendWith(sql []byte, args []any, options Options) ([]byte, []any, error)', 'return AppendWith(sql,args,b,options)'),
    ]:
        doc(lines, name, statement_method_docs[name])
        lines.append(f'{signature} {{ {body} }}\n')
    if t in rowsets:
        lines.append(f'func (*{t}) rowset() {{}}\n')
    lines += ['\n']
emit(root/'statement_methods.go', ''.join(lines))
lines = [header]

# INSERT target columns are selected before a source. The intermediate value
# deliberately has no statement or fluent-clause methods of its own.
doc(lines, 'Columns', fluent_method_docs['Columns'])
lines.append(
    'func (t InsertTarget) Columns(first string, rest ...string) InsertColumnsTarget '
    '{ return newInsertColumnsTarget(t.table, first, rest) }\n'
)
doc(lines, 'Targets', fluent_method_docs['Targets'])
lines.append(
    'func (t InsertTarget) Targets(first Expr, rest ...Expr) InsertColumnsTarget '
    '{ return newInsertExprTarget(t.table, first, rest) }\n\n'
)
for name, args, body, result in [
    ('ValuesSlice', 'values []WriteValue', 'b := &InsertRows{base: t.base()}; return b.ValuesSlice(values)', '*InsertRows'),
    ('Values', 'first WriteValue, rest ...WriteValue', 'b := &InsertRows{base: t.base()}; return b.Values(first, rest...)', '*InsertRows'),
    ('From', 'source Rowset', 'return &InsertSelect{base: t.base(), source: source}', '*InsertSelect'),
    ('DefaultValues', '', 'return &InsertDefaults{base: t.base()}', '*InsertDefaults'),
]:
    doc(lines, name, 'selects one direct value row and copies its structural slice; empty rows fail at render time.' if name == 'ValuesSlice' else fluent_method_docs[name])
    lines.append(f'func (t InsertColumnsTarget) {name}({args}) {result} {{ {body} }}\n')
lines.append('\n')

for t in builders:
    def method(name, args, body, result=None):
        doc_name = name.split('[', 1)[0]
        doc(lines, doc_name, fluent_method_docs[doc_name])
        lines.append(f'func (b *{t}) {name}({args}) {result or "*"+t} {{ {body} }}\n')
    method('With','ctes ...WithQuery','b.base.with=append(b.base.with,ctes...); return b')
    if t != 'MergeBuilder': method('WithRecursive','ctes ...WithQuery','b.base.recursive=true; b.base.with=append(b.base.with,ctes...); return b')
    method('Prefix','parts ...Expr','b.base.prefix=append(b.base.prefix,parts...); return b')
    method('Suffix','parts ...Expr','b.base.suffix=append(b.base.suffix,parts...); return b')
    if t in insert_roles:
        method('Into', 'table string', 'b.base.table=Table(table); return b')
        if t in insert_override_roles:
            method('OverridingSystemValue', '', 'b.base.overriding=overridingSystemValue; return b')
            method('OverridingUserValue', '', 'b.base.overriding=overridingUserValue; return b')
        method('OnConflict[C conflictAction]', 'conflict C', 'setInsertConflict(&b.base,conflict); return b')
        method('Returning', 'expressions ...Expr', 'b.base.returning=append(b.base.returning,expressions...); return b')
        method('ReturningCols', 'columns ...string', 'insertReturningCols(&b.base,columns...); return b')
        method('ReturningRows', 'aliases ReturningAliases', 'b.base.aliases=aliases; return b')
    if t in rowsets:
        method('As','alias string,columns ...string','return Subquery(b,alias,columns...)','Relation')
        method('OrderBy','terms ...Order','b.tail.order=append(b.tail.order,terms...); return b')
        method('RemoveOrderBy','','clear(b.tail.order); b.tail.order=b.tail.order[:0]; return b')
        method('Limit','count int','return b.LimitExpr(limitValue(count))')
        method('LimitExpr','count Expr','b.tail.limit=count; b.tail.hasLimit=true; b.tail.limitAll=false; return b')
        method('RemoveLimit','','b.tail.limit=Expr{}; b.tail.hasLimit=false; b.tail.limitAll=false; return b')
        method('Offset','count int','return b.OffsetExpr(limitValue(count))')
        method('OffsetExpr','count Expr','b.tail.offset=count; b.tail.hasOffset=true; return b')
        method('RemoveOffset','','b.tail.offset=Expr{}; b.tail.hasOffset=false; return b')
        method('LimitAll','','b.tail.limit=Expr{}; b.tail.hasLimit=true; b.tail.limitAll=true; return b')
        method('Fetch','count int,mode FetchMode','return b.FetchExpr(limitValue(count),mode)')
        method('FetchExpr','count Expr,mode FetchMode','b.tail.fetch=count; b.tail.hasFetch=true; b.tail.fetchMode=mode; return b')
        method('RemoveFetch','','b.tail.fetch=Expr{}; b.tail.hasFetch=false; return b')
        if t in {'SelectBuilder','TableBuilder'}: method('Lock','clauses ...LockClause','b.tail.locks=append(b.tail.locks,clauses...); return b')
    lines += ['\n']
emit(root/'fluent.go', ''.join(lines))

# Typed row helpers deliberately stop at arity four; arbitrary-degree Row is
# available without code generation. Values retain their individual Go types.
lines = [header]
for degree in range(2,5):
    letters = [chr(ord('A')+i) for i in range(degree)]
    vars = [x.lower() for x in letters]
    params = ', '.join(x+' any' for x in letters)
    types = ', '.join(letters)
    fields = ', '.join(f'{v} Field[{t}]' for v,t in zip(vars,letters))
    values = ', '.join(f'{v} {t}' for v,t in zip(vars,letters))
    actual = ', '.join(vars)
    exprs = ', '.join(v+'.expr' for v in vars)
    typename = f'Tuple{degree}Expr'
    lines.append(
        f'// {typename} is a statically typed SQL row of degree {degree}. Its type '
        'parameters describe the Go value types accepted by its comparison methods; '
        'they do not validate SQL types or nullability.\n'
    )
    lines.append(f'type {typename}[{params}] struct {{ row RowExpr }}\n')
    doc(lines, f'Tuple{degree}', f'constructs a degree-{degree} row from typed fields in argument order.')
    lines.append(f'func Tuple{degree}[{params}]({fields}) {typename}[{types}] {{ return {typename}[{types}]{{row:Row({exprs})}} }}\n')
    doc(lines, 'Expr', 'returns the underlying row expression.')
    lines.append(f'func (r {typename}[{types}]) Expr() Expr {{ return r.row.Expr() }}\n')
    operators = {'Eq': '=', 'Ne': '<>', 'Lt': '<', 'Lte': '<=', 'Gt': '>', 'Gte': '>='}
    for op in ('Eq','Ne','Lt','Lte','Gt','Gte'):
        doc(lines, f'{op}Values', f'compares r with a row of bound values using SQL {operators[op]}. Values are bound in argument order.')
        lines.append(f'func (r {typename}[{types}]) {op}Values({values}) Condition {{ return r.row.{op}Values({actual}) }}\n')
emit(root/'tuple.go', ''.join(lines))
